[cv]
name = "刘晶"
email = "845472623@qq.com"
phone = "18945696860"

birthday = "1997.10.30"
# 路径
avatar = "研究方向为数学课程与教学论，主要研究数学教育的国际比较、教材与习题研究，以及教育评价理论。"

[[educations]]
school = "石河子大学"
major = "课程与教学论"
degree = "硕士在读"
date = "2023.09 - now"
[[educations]]
school = "哈尔滨师范大学"
major = "数学与应用数学"
degree = "学士"
date = "2016.09 - 2020.06"

[[projects]]
name = "一作文章《中丹初中数学习题的比较研究—以函数为例》已被《数学教育学报》录用"
date = "2025.05"

[[projects]]
name = "二作文章《丹麦初中数学教科书跨学科主题学习项目的设置与启示》发表于《教学与管理》（导师一作）"
date = "2025.09"

[[projects]]
name = "一篇关于中丹教科书习题核心素养比较的文章已投《数学通报》，目前正在返修"
date = "2025.11"

[[projects]]
name = "一篇关于数学习题难度模型的文章已投《课程·教材·教法》"
date = "2025.10"

[[awards]]
name = "20205年度国家奖学金已公示"
date = "2025.10"

[[skills]]
name = "CET6 445分"


